version: "3.8"
services:
  kafka:
    image: redpandadata/redpanda:v23.3.12
    container_name: kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://${RENDER_INTERNAL_HOSTNAME:-localhost}:9092
    ports:
      - "9092:9092"
