# render.yaml
# Services for deploying the real-time ML pipeline on Render.

services:
  # 1) Kafka (Redpanda) as a Private Service
  - type: pserv
    name: kafka
    env: docker
    image: redpandadata/redpanda:v23.3.12
    plan: starter
    dockerCommand: >
      redpanda start
      --overprovisioned --smp=1 --memory=1G --reserve-memory=0M --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://${RENDER_INTERNAL_HOSTNAME}:9092

  # 2) Streamlit Dashboard (Web)
  - type: web
    name: dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard/training_monitor.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: KAFKA_BOOTSTRAP
        fromService:
          type: pserv
          name: kafka
          property: hostport

  # 3) Data Producer (Worker)
  - type: worker
    name: producer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ingestion/producer.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: KAFKA_BOOTSTRAP
        fromService:
          type: pserv
          name: kafka
          property: hostport

  # 4) Bronze Consumer (Worker)
  - type: worker
    name: bronze-consumer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python transform/consumer_to_parquet.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: KAFKA_BOOTSTRAP
        fromService:
          type: pserv
          name: kafka
          property: hostport

  # 5) Silver Consumer (Worker)
  - type: worker
    name: silver-consumer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python transform/consumer_to_silver.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: KAFKA_BOOTSTRAP
        fromService:
          type: pserv
          name: kafka
          property: hostport

  # 6) Trainer (Worker)
  - type: worker
    name: trainer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python transform/consumer_trainer.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
